### PR TITLE
Configurable filtering of firehose events.

### PR DESCRIPTION
**Pull request by fluffle**
This change is [Reviewable](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/165)

### CODE REVIEW

**Comment by fluffle** [comment]
Hi Jeff,

I want to stress that this is not 100% complete yet. I didn't want to lose out on a round trip to the west coast, so I've sent you something that's broadly done but needs a fair bit of polish. As such, don't feel like you need to do a line-by-line review, I'm more interested in you questioning my design choices and implementation aesthetics :-)

Nothing's set in stone here, and I'd like to know if you want a major rework of any of what's here before I attempt to test this more thoroughly.

Cheers,
--alex

**Comment by johnsonj** [comment]
Design looks good to me. Comment below about order of how the filters are applied but minor.

We may need to tweak the configuration so we can give tile users a good experience (to add individual blacklist/whitelist entries) but the proposed JSON structure is appropriate.

---

Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/stackdriver-nozzle/app/builder.go, line 93 at r1](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L-s-u_P6-hKGF92j0JD:-L-s-u_P6-hKGF92j0JE:b-vvgg5r) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/e276fa001df9ab1e1451c7537877add9a76200ef/src/stackdriver-nozzle/app/builder.go#L93)):*
> wFil

---

*[src/stackdriver-nozzle/nozzle/event_filter.go, line 75 at r1](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L-s0dmrqZSe1hbL6-0T:-L-s0dmrqZSe1hbL6-0U:b-q74txj) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/e276fa001df9ab1e1451c7537877add9a76200ef/src/stackdriver-nozzle/nozzle/event_filter.go#L75)):*
> ```Go
> // of the filters added to the MetricFilter.
> func (ef *EventFilter) Match(event *events.Envelope) bool {
> 	if ef == nil {
> ```

great!

---

*[src/stackdriver-nozzle/nozzle/filter_sink.go, line 67 at r1](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L-s-zDOC9aS59Uz9tJ2:-L-s-zDOC9aS59Uz9tJ3:boh893f) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/e276fa001df9ab1e1451c7537877add9a76200ef/src/stackdriver-nozzle/nozzle/filter_sink.go#L67)):*
> ```Go
> 
> func (fs *filter) Receive(event *events.Envelope) {
> 	if fs.isBlacklisted(event) {
> ```

probably best to do the EventType filtering first

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-:-L-s0OiT7YfPhXwGtDuc:b-e6617p)*

**Comment by fluffle** [comment]
I have some ideas about the configuration but I think I am gonna need help with the implementation.

My plan was to use erb to template out the json from an identical YAML data structure in the manifest. There's some prior art for this kind of thing around in the ERT already, so I think I can figure it out. But I am not sure how to present a meaningful interface to the user in the tile config, so they can add new filters and e.g. choose the sink + type from dropdowns. Do you know of good places to learn / cargo cult from?

---

Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/stackdriver-nozzle/nozzle/filter_sink.go, line 67 at r1](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L-s-zDOC9aS59Uz9tJ2:-L04-pGAr6PmKTAAcf0q:b7e49t6) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/e276fa001df9ab1e1451c7537877add9a76200ef/src/stackdriver-nozzle/nozzle/filter_sink.go#L67)):*
<details><summary><i>Previously, johnsonj (Jeff Johnson) wrote…</i></summary><blockquote>

probably best to do the EventType filtering first
</blockquote></details>

Sure, I can do that. I'll add a separate metric for it, too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-:-L04-v080545eNv5YmYI:b-95zd1s)*

**Comment by fluffle** [comment]
On the subject of configuration: How can one test the templating of files for a bosh release? I have something that I think might work enough that the inevitable failure will help me iterate towards correctness :-)

Also: would you prefer everything done in one PR or do you want to review and merge the nozzle changes separately from the bosh spec changes?

---

Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/stackdriver-nozzle/nozzle/event_filter.go, line 75 at r1](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L-s0dmrqZSe1hbL6-0T:-L04JuBpWmLoRSqPPSdJ:b-7kyj7a) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/e276fa001df9ab1e1451c7537877add9a76200ef/src/stackdriver-nozzle/nozzle/event_filter.go#L75)):*
<details><summary><i>Previously, johnsonj (Jeff Johnson) wrote…</i></summary><blockquote>

great!
</blockquote></details>

I did debate doing this in Add() as well, for lazy allocation of filters. WDYT?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-:-L05L-ZrfGptyJkwkBZU:b-6issnm)*

**Comment by johnsonj** [comment]
Here's an example tile[1] where we have dropdowns/collection of user choices. Unfortunately it is not a BOSH release, but the tile ends up presenting JSON to the CF app so it might do the same a BOSH release. I wonder if it applies though because we aren't a service broker. I can connect you with the right folks at Pivotal to help with the tile specifics when it's time if needed. 

To test it you need to be deploying to a BOSH director locally. You see if BOSH Lite[2] looks worth it to you, we have an example manifest that deploys the nozzle [3]. It will give you a faster iteration cycle then a full fledged director. 

In terms of config vs nozzle changes- I recommend splitting for your own sanity since the config will likely be lots of iterating to get right. 

[1] https://github.com/GoogleCloudPlatform/gcp-service-broker/blob/master/tile.yml#L393
[2] https://bosh.io/docs/bosh-lite
[3] https://github.com/cloudfoundry-community/stackdriver-tools/blob/develop/manifests/stackdriver-tools-bosh-lite.yml

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/stackdriver-nozzle/nozzle/event_filter.go, line 75 at r1](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L-s0dmrqZSe1hbL6-0T:-L073VAuuyDxqciIG29T:bw5t5eu) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/e276fa001df9ab1e1451c7537877add9a76200ef/src/stackdriver-nozzle/nozzle/event_filter.go#L75)):*
<details><summary><i>Previously, fluffle (Alex Bee) wrote…</i></summary><blockquote>

I did debate doing this in Add() as well, for lazy allocation of filters. WDYT?
</blockquote></details>

I'd say default for stateless and let the panic happen for non-stateless. I can't figure out what a default Add would do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-:-L070vzFr9RJcgd_oyYH:b7ys4bv)*

**Comment by fluffle** [comment]
I've cargo culted like crazy, I give this about a 10% chance of working as it is now. How do I build it into a tile? I need to deploy the entire thing to PCF to test e2e and validate that the forms look like I hope they do.

I think this ought to be reviewable now, modulo verifying that it actually DTRT. PTAL? :-)

---

Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-:-L0BHfSCg_LiFuVk3nKs:b7uvpld)*

**Comment by johnsonj** [comment]
[tile build example](https://github.com/cloudfoundry-community/stackdriver-tools/blob/develop/ci/tasks/build-tile.sh#L20) from CI. You could either use the docker container ([like CI](https://github.com/cloudfoundry-community/stackdriver-tools/blob/develop/ci/tasks/build-tile.yml#L4)) or download the [tile generator](http://docs.pivotal.io/tiledev/1-12/tile-generator.html#how-to). I'll give this a go at a full review.

**Comment by johnsonj** [comment]
Reviewed 4 of 8 files at r1, 1 of 2 files at r2, 3 of 3 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[tile.yml.erb, line 151 at r4](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L0CohPnFh5-Q68R0giU:-L0CohPnFh5-Q68R0giV:bwphdjy) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/44eb8fd2a1566953216240150dce8f6df112bbee/tile.yml.erb#L151)):*
> ```erb
>     type: collection
>     label: Event Blacklist
>     configurable: true
> ```

This looks good- but I have no idea :) 

---

*[jobs/stackdriver-nozzle/templates/event_filters.json.erb, line 2 at r4](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L0Ck84q8CbCw-QpVCOp:-L0Ck84r8qRh12U9GQl1:b-898ytj) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/44eb8fd2a1566953216240150dce8f6df112bbee/jobs/stackdriver-nozzle/templates/event_filters.json.erb#L2)):*
> ```erb
> {<% if_p('nozzle.event_filter.blacklist') do |blacklist| %>
>   "blacklist": [<% blacklist.each_with_index do |filter, index| %>
> ```

you're in ruby- use the force!

```erb
<%
require 'json'
config = {}
config["blacklist"] = p('nozzle.event_filter.blacklist') if p('nozzle.event_filter.blacklist')
# .. whitelist
%>

<%=config.to_json %>
```

---

*[src/stackdriver-nozzle/README.md, line 65 at r4](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L0Cl4yf1z0qizBdsBbr:-L0Cl4yf1z0qizBdsBbs:bxrqs3y) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/44eb8fd2a1566953216240150dce8f6df112bbee/src/stackdriver-nozzle/README.md#L65)):*
> ```Markdown
>   firehose; defaults to `stackdriver-nozzle`
> 
> #### Event Filters
> ```

great docs!

---

*[src/stackdriver-nozzle/app/builder.go, line 76 at r4](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L0CnWcOSYm6zj1S011P:-L0CnWcOSYm6zj1S011Q:bss07qv) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/44eb8fd2a1566953216240150dce8f6df112bbee/src/stackdriver-nozzle/app/builder.go#L76)):*
> ```Go
> 
> 	logAdapter := a.newLogAdapter()
> 	filteredLogSink, err := nozzle.NewFilterSink(logEvents, nil, nil,
> ```

do you need to pipe in the new EventFilter here and at creation of filteredMetricSink?

---

*[src/stackdriver-nozzle/config/config.go, line 104 at r4](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L0ClYok3wZFdj9SUwsT:-L0ClYok3wZFdj9SUwsU:bg2w0wq) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/44eb8fd2a1566953216240150dce8f6df112bbee/src/stackdriver-nozzle/config/config.go#L104)):*
> ```Go
> 	LogWhitelist    *nozzle.EventFilter
> 	MetricBlacklist *nozzle.EventFilter
> 	MetricWhitelist *nozzle.EventFilter
> ```

I wonder if we should switch to 'LoggingBlacklist', 'MonitoringBlacklist'? We seem to be going the long term path of not making such a distinction between Cloud Foundry Logs/Metrics but instead to make the distinction of which Stackdriver endpoint we write to. 

---

*[src/stackdriver-nozzle/config/config.go, line 104 at r4](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L0Co9yH8e4XaQVR692G:-L0Co9yH8e4XaQVR692H:boqncq9) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/44eb8fd2a1566953216240150dce8f6df112bbee/src/stackdriver-nozzle/config/config.go#L104)):*
> ```Go
> 	LogWhitelist    *nozzle.EventFilter
> 	MetricBlacklist *nozzle.EventFilter
> 	MetricWhitelist *nozzle.EventFilter
> ```

A small design change to consider is having these be lists of data instead of a concrete filter (`[]EventFilterRule`) and moving the construction of the `EventFilter` in `app/builder.go`.

This keeps the config package concerned with JSON parsing/loading and does not add the  dependency between config/nozzle.,

---

*[src/stackdriver-nozzle/nozzle/event_filter.go, line 75 at r1](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L-s0dmrqZSe1hbL6-0T:-L0CmDzSv9Xjz3W1MnFg:byhdwdi) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/e276fa001df9ab1e1451c7537877add9a76200ef/src/stackdriver-nozzle/nozzle/event_filter.go#L75)):*
<details><summary><i>Previously, fluffle (Alex Bee) wrote…</i></summary><blockquote>

It moves the allocation of the actual event filter struct from config.go (lines 201-202) to here, where we'd do:

```Go
if ef == nil {
    *ef = EventFilter{}
}
```

In general my perspective would be that anyone Adding to a filter should probably already have an allocated one to add to, but here we're only allocating when filters are known to exist anyway so it's a bit moot.
</blockquote></details>

I see! Looks good to me as is. 

---

*[src/stackdriver-nozzle/nozzle/filter_sink.go, line 33 at r4](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L0Cmpkw2d1uyH_O-j88:-L0Cmpkw2d1uyH_O-j89:b-9pl6ft) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/44eb8fd2a1566953216240150dce8f6df112bbee/src/stackdriver-nozzle/nozzle/filter_sink.go#L33)):*
> ```Go
> func init() {
> 	filteredEvents = telemetry.NewCounter(telemetry.Nozzle, "filter_sink.filtered_events")
> 	blacklistedEvents = telemetry.NewCounter(telemetry.Nozzle, "filter_sink.blacklisted_events")
> ```

should we log whitelisted too or is that noise? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165)*

**Comment by fluffle** [comment]
Addressed comments and rebased to latest develop. I've not had time to attempt tile generation with docker yet, sorry.

---

Review status: 4 of 15 files reviewed at latest revision, 7 unresolved discussions.

---

*[tile.yml.erb, line 151 at r4](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L0CohPnFh5-Q68R0giU:-L0KDf7P4VMoD4Bz4gEK:bu2k6mm) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/44eb8fd2a1566953216240150dce8f6df112bbee/tile.yml.erb#L151)):*
<details><summary><i>Previously, johnsonj (Jeff Johnson) wrote…</i></summary><blockquote>

This looks good- but I have no idea :) 
</blockquote></details>

I know right? Hopefully some testing will show whether any of this is remotely correct.

---

*[jobs/stackdriver-nozzle/templates/event_filters.json.erb, line 2 at r4](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L0Ck84q8CbCw-QpVCOp:-L0KCwsoB7PMqKV-LYuK:b-11inwl) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/44eb8fd2a1566953216240150dce8f6df112bbee/jobs/stackdriver-nozzle/templates/event_filters.json.erb#L2)):*
<details><summary><i>Previously, johnsonj (Jeff Johnson) wrote…</i></summary><blockquote>

you're in ruby- use the force!

```erb
<%
require 'json'
config = {}
config["blacklist"] = p('nozzle.event_filter.blacklist') if p('nozzle.event_filter.blacklist')
# .. whitelist
%>

<%=config.to_json %>
```
</blockquote></details>

That is *sooooo* much nicer, thanks! I am not at all familiar with Ruby or ERB :-)

---

*[src/stackdriver-nozzle/README.md, line 65 at r4](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L0Cl4yf1z0qizBdsBbr:-L0KDmUzXa987z-ZPI_l:b-idoics) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/44eb8fd2a1566953216240150dce8f6df112bbee/src/stackdriver-nozzle/README.md#L65)):*
<details><summary><i>Previously, johnsonj (Jeff Johnson) wrote…</i></summary><blockquote>

great docs!
</blockquote></details>

Thanks! I figure it's about the only way the feature will get used by anyone other than us.

---

*[src/stackdriver-nozzle/app/builder.go, line 76 at r4](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L0CnWcOSYm6zj1S011P:-L0KDtbCTJIpAYjz-5X5:bwe4q59) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/44eb8fd2a1566953216240150dce8f6df112bbee/src/stackdriver-nozzle/app/builder.go#L76)):*
<details><summary><i>Previously, johnsonj (Jeff Johnson) wrote…</i></summary><blockquote>

do you need to pipe in the new EventFilter here and at creation of filteredMetricSink?
</blockquote></details>

Yes, I totally do, thanks!

---

*[src/stackdriver-nozzle/config/config.go, line 104 at r4](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L0ClYok3wZFdj9SUwsT:-L0KGQwSUJZ9xYGskO92:b8bof47) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/44eb8fd2a1566953216240150dce8f6df112bbee/src/stackdriver-nozzle/config/config.go#L104)):*
<details><summary><i>Previously, johnsonj (Jeff Johnson) wrote…</i></summary><blockquote>

I wonder if we should switch to 'LoggingBlacklist', 'MonitoringBlacklist'? We seem to be going the long term path of not making such a distinction between Cloud Foundry Logs/Metrics but instead to make the distinction of which Stackdriver endpoint we write to. 
</blockquote></details>

Sure, I can do that.

---

*[src/stackdriver-nozzle/config/config.go, line 104 at r4](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L0Co9yH8e4XaQVR692G:-L0KRO1GDXGfybHPSUmC:b-llxt2i) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/44eb8fd2a1566953216240150dce8f6df112bbee/src/stackdriver-nozzle/config/config.go#L104)):*
<details><summary><i>Previously, johnsonj (Jeff Johnson) wrote…</i></summary><blockquote>

A small design change to consider is having these be lists of data instead of a concrete filter (`[]EventFilterRule`) and moving the construction of the `EventFilter` in `app/builder.go`.

This keeps the config package concerned with JSON parsing/loading and does not add the  dependency between config/nozzle.,
</blockquote></details>

Urgh, this forced me to be much more stringent with my testing. Took a bit of messing around, but sure, it's done.

---

*[src/stackdriver-nozzle/nozzle/filter_sink.go, line 33 at r4](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L0Cmpkw2d1uyH_O-j88:-L0KHBQu-iR_onKNYRYo:b-cghxsm) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/44eb8fd2a1566953216240150dce8f6df112bbee/src/stackdriver-nozzle/nozzle/filter_sink.go#L33)):*
<details><summary><i>Previously, johnsonj (Jeff Johnson) wrote…</i></summary><blockquote>

should we log whitelisted too or is that noise? 
</blockquote></details>

Specifically blacklisted-but-also-whitelisted would be useful, I think. Good idea!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-:-L0Ki6nS3xLvuyHI9Yzz:b958ihb)*

**Comment by fluffle** [comment]
OK, I am pretty sure this is ready to go now. I shared a tile built from the current HEAD of the PR branch so you can test it yourself if necessary. Here's a couple of screens of the event filter config page for examination:




PTAL?

---

Review status: 4 of 15 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/stackdriver-nozzle/nozzle/filter_sink.go, line 33 at r4](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L0Cmpkw2d1uyH_O-j88:-L0j5-u2rGvy94X2Ij-M:b6h2cse) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/44eb8fd2a1566953216240150dce8f6df112bbee/src/stackdriver-nozzle/nozzle/filter_sink.go#L33)):*
<details><summary><i>Previously, fluffle (Alex Bee) wrote…</i></summary><blockquote>

Specifically blacklisted-but-also-whitelisted would be useful, I think. Good idea!
</blockquote></details>

Now I've got this working end-to-end it is obvious in hindsight that having a metric for "filtered_events" is not helpful when we are explicitly using this to direct some parts of the event stream to one sink and other parts to a different one, because we are therefore *expecting* many events to be filtered. So I'm going to remove this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-:-L0j7C2FH0jXHzWSMfz9:bbxmysw)*

**Comment by johnsonj** [comment]
This is looking really great. 

Do you think the filter UI needs a name or description field? If I wanted to configure:
```json
- {"regex":".*","type":"job", "sink":"all"}
- {"regex":".*","type":"name", "sink":"all"}
```

They'd both show up as '.*' in the UI once created. I yield to you here if you think that's a valid example or if it's too contrived.

---

Review status: 4 of 15 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-:-L0lky2pIq-g5TifEjam:bw4t46g)*

**Comment by knyar** [comment]
Review status: 4 of 15 files reviewed at latest revision, 9 unresolved discussions.

---

*[tile.yml.erb, line 141 at r5](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L0o2hs0RB4Q0UG_GjTR:-L0o2hs0RB4Q0UG_GjTS:bsxwbml) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/ac1bf1b24c05ee60ec0e1649002b15bbab71f5df/tile.yml.erb#L141)):*
> ```erb
>     *   A *regexp*, which must be a valid regular expression.
>     *   A *type*, which may be either "name" or "job".
>         *   *name* matches against a concatenation of event _origin_ and metric _name_,
> ```

Should we mention that origin and name are concatenated with a "."?
(same for README.md)

---

*[src/stackdriver-nozzle/nozzle/event_filter.go, line 27 at r5](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L0o28gAL0UL6Rdtp3ag:-L0o28gAL0UL6Rdtp3ah:b-59m9fy) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/ac1bf1b24c05ee60ec0e1649002b15bbab71f5df/src/stackdriver-nozzle/nozzle/event_filter.go#L27)):*
> ```Go
> )
> 
> type matchType string
> ```

Is this used anywhere?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165)*

**Comment by fluffle** [comment]
I was not expecting the individual list elements to be named like this and I agree it's a little problematic. I'd prefer it if the element showed all three components when collapsed but I don't know how to achieve this or whether it's even possible. Adding an optional description field (which will be ignored in the Nozzle) seems like a reasonable solution.

---

Review status: 4 of 15 files reviewed at latest revision, 9 unresolved discussions.

---

*[tile.yml.erb, line 141 at r5](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L0o2hs0RB4Q0UG_GjTR:-L0sMRVnA4fJrO7Upqbp:b-8hp75n) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/ac1bf1b24c05ee60ec0e1649002b15bbab71f5df/tile.yml.erb#L141)):*
<details><summary><i>Previously, knyar (Anton Tolchanov) wrote…</i></summary><blockquote>

Should we mention that origin and name are concatenated with a "."?
(same for README.md)
</blockquote></details>

Yes. Giving an example is probably worthwhile too.

---

*[src/stackdriver-nozzle/nozzle/event_filter.go, line 27 at r5](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-L0o28gAL0UL6Rdtp3ag:-L0sKUbSgr6DZYbCL5sg:b-wpoa3g) ([raw file](https://github.com/cloudfoundry-community/stackdriver-tools/blob/ac1bf1b24c05ee60ec0e1649002b15bbab71f5df/src/stackdriver-nozzle/nozzle/event_filter.go#L27)):*
<details><summary><i>Previously, knyar (Anton Tolchanov) wrote…</i></summary><blockquote>

Is this used anywhere?
</blockquote></details>

Ah, good spot. I was going to type the match types, but because they're coming from JSON it was easier not to -- it avoids pointless type-casting hoop jumping,

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-:-L0sNAGVHiEVl3u8t42a:b-grlfof)*

**Comment by fluffle** [comment]
Hi Jeff, are you waiting for anything else from me w.r.t this PR? I think it's ready to be merged; I've been keeping up with rebases to develop so you should be ok to pull the trigger when you're happy.

**Comment by johnsonj** [comment]
I'll give it the fine tooth review today

**Comment by johnsonj** [comment]
:lgtm: awesome work on this, thank you and sorry for the delay!

---

Reviewed 8 of 11 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cloudfoundry-community/stackdriver-tools/165#-:-L2SqKw1McQ3aMQel37H:b-d35755)*

**Pull request merged**
